version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: react
        versions:
          - ">= 0"
      - dependency-name: react-dom
        versions:
          - ">= 0"
    commit-message:
      prefix: chore
      include: scope
